### ISSUE TITLE
Remove libp2p-crypto dep

### ISSUE THREAD

**Issue by daviddias** [ipfs/interface-datastore#10]
Currently, libp2p is a dep just for the `randomBytes` function. This is a bit of overkill. We can reduce the size of the module if we do that.

**Comment by thisconnect** [comment]
could we change from `crypto = require('libp2p-crypto')` to `randomBytes = require('libp2p-crypto/src/random-bytes')`

**Comment by thisconnect** [comment]
### Summary
I opened 2 PR's, one using builtin `crypto` vs. `webcrypto`. Tested against https://github.com/ipfs/js-datastore-core (sorry for the noise).

Expected the `crypto` version to fail in browser test and `webcrypto` to pass. Unfortunately it looks as if it is the exact opposite, `crypto` did succeed and `webcrypto` failed :/

Results
- `crypto`
  - https://github.com/ipfs/interface-datastore/pull/15 PASS
  - https://github.com/ipfs/js-datastore-core/pull/7 PASS
- `webcrypto`
  - https://github.com/ipfs/interface-datastore/pull/16 FAIL
  - https://github.com/ipfs/js-datastore-core/pull/8 FAIL

Looks like browser tests passed, but only webworker failed https://travis-ci.org/ipfs/js-datastore-core/jobs/297189411#L2411

Guessing
I suspect `crypto` is detected and shimmed during the build step somehow and therefore it passed. Not sure why `webcrypto` it failed in the webworker.

cc @diasdavid @richardschneider

**Comment by daviddias** [comment]
Thank you @thisconnect :) Looks good to me (comfortable since it is a devDep). Merged now :)
