### ISSUE TITLE
Require opening of datastore - lack of async

### ISSUE THREAD

**Issue by AuHau** [ipfs/interface-datastore#28]
I believe that small shortcoming of opening datastore directly in constructor of the implementation instead of requiring calling `open()` before any usage is that it is not possible to use async in the constructor.

Not sure how big improvement it would be and not sure how worthy such a change would be since it would have to be a breaking change, but still wanted to mention it.

**Comment by achingbrain** [comment]
`.open()` is a separate method that can be async now so I think this is ok to close.
