### ISSUE TITLE
Fix sharding query

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/interface-datastore#3]
Currently the test suite fails for sharding stores, because the query is not fully translated for to handle the sharding keys.

Missing translation are `prefix` and `orders`. I am not sure what's the issue with `orders`

**Comment by richardschneider** [comment]
This is fixed in  *sharding and query for windows interop* ([#6](https://github.com/ipfs/js-datastore-core/issues/6)) ([845316d](https://github.com/ipfs/js-datastore-core/commit/845316d))
