### ISSUE TITLE
Additional types maintainer(s)?

### ISSUE THREAD

**Issue by carsonfarmer** [ipfs/interface-datastore#44]
I'm am currently the only maintainer of the Typescript Types for this and a few other repos. However, it would be great if anyone else would be interested in being listed as a maintainer to ease future updates. This is not a requirement, just a request! As a side note, what is the likelihood that we could simply include the types in this repo directly?

Context: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46416#issuecomment-665309201

**Comment by achingbrain** [comment]
> we could simply include the types in this repo directly

That'd be great, as long as it's done in the JSDoc style so there aren't extra places to update type information that will invariably get missed.
