### ISSUE TITLE
[Request] make getAll() part of API spec

### ISSUE THREAD

**Issue by HexaField** [ipfs/interface-datastore#60]
There are discrepancies between the different datastore implementations regarding retrieving all entries in a datastore. `MemoryDatastore` takes no parameters, whereas `datastore-fs` requires an object to be passed, and `datastore-level` has no implementation.

If this function is exposed in the core `interface-datastore` API, this can be standardised.

**Comment by achingbrain** [comment]
There is no `getAll` function for datastores - there's [getMany](https://github.com/ipfs/interface-datastore#getmanysource-options---asynciteratoruint8array) which allows you to look up many keys and [_all](https://github.com/ipfs/interface-datastore/blob/master/src/adapter.js#L132) which is used internally by the [adapter](https://github.com/ipfs/interface-datastore/blob/master/src/adapter.js) when `.query` is invoked, which may be what you are thinking of?

If you want to iterate over every value in a datastore you would issue an empty query:

```js
for await (const entry of store.query()) {
  // .. loop over every entry
}
```

The `query` and any `options` are passed through to allow the implementation to perform any optimisations based on the query, in case it's expensive to return every single datastore value - if it's over a network for example.

This could be better documented in the README under the [adapter section](https://github.com/ipfs/interface-datastore/blob/master/README.md#adapter), would you like to have a go at a PR that clarifies this?

**Comment by HexaField** [comment]
Thanks for the clarification. Sometimes a bit of RTFM is all you need lol! I will try and remember to look at making a PR on the docs soon.
